import {useState} from 'react';import {ArrowDownRight,ArrowUpRight,Check,Clock,Dumbbell,MapPin,Quote,Users} from 'lucide-react';import {Header,Booking,Lightbox} from './components';import {pics,plans,coaches} from './data';
const trainings=[['Силовые тренировки','Работа с весами для набора силы и мышечной массы.','strength'],['Функциональный тренинг','Развивай выносливость, силу и координацию.','functional'],['Персональные тренировки','Индивидуальная программа и тренер рядом.','personal'],['Кардио','Тренировки для выносливости и общего тонуса.','cardio']];const gallery=[pics.gym,pics.strength,pics.functional,pics.personal,pics.cardio,pics.hero];
export default function App(){const[booking,setBooking]=useState(false),[period,setPeriod]=useState(1),[light,setLight]=useState<number|null>(null);const factor=period===1?1:period===3?.93:0.82;return <><Header book={()=>setBooking(true)}/><main><section id="home" className="hero" style={{backgroundImage:`linear-gradient(90deg,#090a0b 7%,#090a0ba8 50%,#090a0b28),url(${pics.hero})`}}><div className="hero-content"><p className="kicker">FITNESS CLUB · 24/7</p><h1>СТАНЬ<br/><em>СИЛЬНЕЕ.</em></h1><p className="lead">Современный фитнес-клуб для тех, кто хочет видеть результат, а не искать оправдания.</p><div className="actions"><button className="button" onClick={()=>setBooking(true)}>Записаться на тренировку <ArrowUpRight size={17}/></button><a href="#prices" className="button ghost">Посмотреть цены</a></div></div><div className="hero-stats">{[['500+','участников'],['30+','тренажёров'],['12','тренеров'],['24/7','доступ']].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><a className="scroll" href="#about">Листай ниже <ArrowDownRight size={16}/></a></section>
<section id="about" className="section"><p className="kicker">01 — ПОЧЕМУ МЫ</p><h2>ЗАЛ, В КОТОРОМ ХОЧЕТСЯ<br/><em>ТРЕНИРОВАТЬСЯ</em></h2><div className="benefits">{[['01','Современное оборудование','Всё необходимое для эффективных тренировок.'],['02','Профессиональные тренеры','Поможем поставить технику и составить программу.'],['03','24/7 доступ','Тренируйся тогда, когда удобно тебе.'],['04','Комьюнити','Окружение людей, которые тоже работают над собой.']].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><ArrowUpRight/></article>)}</div></section>
<section id="training" className="section dark-section"><p className="kicker">02 — НАПРАВЛЕНИЯ</p><h2>ВЫБЕРИ СВОЮ <em>ЦЕЛЬ</em></h2><div className="training-grid">{trainings.map(([n,d,p])=><article className="training-card" key={n}><img src={pics[p as keyof typeof pics]} alt={n}/><div><h3>{n}</h3><p>{d}</p><button onClick={()=>setBooking(true)}>Подробнее <ArrowUpRight size={17}/></button></div></article>)}</div></section>
<section id="prices" className="section"><p className="kicker">03 — АБОНЕМЕНТЫ</p><h2>ВЫБЕРИ СВОЙ <em>АБОНЕМЕНТ</em></h2><div className="period"><button className={period===1?'active':''} onClick={()=>setPeriod(1)}>Месяц</button><button className={period===3?'active':''} onClick={()=>setPeriod(3)}>3 месяца <small>−7%</small></button><button className={period===12?'active':''} onClick={()=>setPeriod(12)}>12 месяцев <small>−18%</small></button></div><div className="plans">{plans.map(([n,p,features])=><article className={'plan '+(n==='PRO'?'featured':'')} key={n}>{n==='PRO'&&<b className="popular">ПОПУЛЯРНЫЙ</b>}<h3>{n}</h3><p className="price">{Math.round(Number(p)*factor).toLocaleString('uk-UA')} <small>грн / мес.</small></p><ul>{features.map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul><button className={'button '+(n==='PRO'?'':'ghost')} onClick={()=>setBooking(true)}>Выбрать</button></article>)}</div></section>
<section id="coaches" className="section dark-section"><p className="kicker">04 — КОМАНДА</p><h2>ЛЮДИ, КОТОРЫЕ ВЕДУТ<br/>К <em>РЕЗУЛЬТАТУ</em></h2><div className="coach-grid">{coaches.map(([n,s,e,p])=><article className="coach" key={n}><img src={pics[p as keyof typeof pics]} alt={`Тренер ${n}`}/><div className="coach-overlay"><p>{e}</p><button onClick={()=>setBooking(true)}>Записаться <ArrowUpRight size={16}/></button></div><h3>{n}</h3><p>{s}</p></article>)}</div></section>
<section id="gallery" className="section"><p className="kicker">05 — ПРОСТРАНСТВО</p><h2>ТВОЯ НОВАЯ <em>ТЕРРИТОРИЯ</em></h2><div className="gallery">{gallery.map((img,i)=><button key={img} onClick={()=>setLight(i)}><img src={img} alt="Интерьер и тренировки IRON DISTRICT"/></button>)}</div></section>
<section className="section testimonials"><p className="kicker">06 — ОТЗЫВЫ</p><h2>ЧТО ГОВОРЯТ <em>УЧАСТНИКИ</em></h2><div>{['За 4 месяца наконец начал видеть результат. Очень нравится оборудование и атмосфера.','Тренеры реально помогают, а не просто ходят по залу.','Зал, в который хочется возвращаться даже после тяжёлого дня.'].map((t,i)=><article key={t}><Quote/><p>★★★★★</p><blockquote>«{t}»</blockquote><small>{['Артём, 25','Мария, 29','Влад, 31'][i]}</small></article>)}</div></section>
<section id="contacts" className="contact section"><div><p className="kicker">07 — КОНТАКТЫ</p><h2>НАЙДИ <em>НАС</em></h2><p><MapPin/> ул. Спортивная, 15</p><p><Clock/> Пн–Вс: 24/7</p><p><Dumbbell/> +380 00 000 00 00</p><a href="mailto:hello@irondistrict.example">hello@irondistrict.example</a></div><div className="map"><span>IRON<br/>DISTRICT</span><i></i><small>ул. Спортивная, 15</small></div></section>
<section className="cta"><p className="kicker">ТВОЙ РЕЗУЛЬТАТ НАЧИНАЕТСЯ ЗДЕСЬ</p><h2>ГОТОВ<br/><em>НАЧАТЬ?</em></h2><p>Первая тренировка — лучший момент начать.</p><button className="button" onClick={()=>setBooking(true)}>Записаться на тренировку <ArrowUpRight size={17}/></button></section></main><footer><div className="logo">IRON<span>•</span>DISTRICT</div><p>Твоя сила. Твой результат.</p><div><a href="#home">Instagram</a><a href="#home">Telegram</a><a href="#home">TikTok</a></div><small>© 2026 IRON DISTRICT · Политика конфиденциальности</small></footer>{booking&&<Booking close={()=>setBooking(false)}/>} {light!==null&&<Lightbox images={gallery} index={light} close={()=>setLight(null)}/>}</>}

